---
containers:
  - service_name: heimdall
    active: true
    image: lscr.io/linuxserver/heimdall:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/opt/appdata/heimdall:/config"
    restart: unless-stopped
