---
# Fozzie is my media server, connected to a couple of hard drive arrays.

- name: Set up Fozzie
  hosts: all
  vars_files:
    - 'vars/main.yml'
    - 'vars/vault.yml'

  become: true
  pre_tasks:
    - name: Ensure packages are updated and upgraded
      ansible.builtin.import_role:
        name: packages
      vars:
        upgrade_packages: true

  roles:
    - role: common
    - role: motd
    # - role: fozzie_network
    #   tags: testing
    - role: fozzie_drives
      tags: drives
    - role: geerlingguy.docker
      tags: jeff
    - role: ironicbadger.docker_compose_generator
    - role: bhawkins-user
      tags: testing
    # - role: artis3n.tailscale
    #   tags: tailscale
    - role: vladgh.samba.server
      tags: samba
      vars:
        # samba_users comes from vault
        samba_mitigate_cve_2017_7494: false
        samba_apple_extensions: "yes"
