all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_method: sudo
  children:
    vms:
      hosts:
        scooter:
          user: bhawkins
          user_passwd: "{{ host_user_passwd }}"
          root_passwd: "{{ host_root_passwd }}"
          ssh_pub_key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
          ansible_become_pass: "{{ host_user_passwd }}"
          cfg_static_network: false
        zoot:
          user: root
          