- name: Set up my bhawkins user
  hosts: all
  remote_user: bhawkins
  become: true
  roles:
    - role: packages
      upgrade_packages: false
    - zsh
    - role: mariuskimmina.dotfiles
      user_home: /home/bhawkins

  tasks:
    - name: Make sure bhawkins user is created
      ansible.builtin.user:
        name: bhawkins
        comment: Brad Hawkins
        groups:
          - users
          - sudo
          - adm
        createhome: true
        home: /home/bhawkins
        shell: /bin/zsh
        state: present
