- name: New user setup
  hosts: testing
  become: true
  roles:
    - packages
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: print message
      ansible.builtin.debug:
        msg: Hello World
 