- name: New user setup
  hosts: all
  become: true
  roles:
    - packages
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello World
