---
roles:
  - name: geerlingguy.dotfiles
  - name: geerlingguy.docker
  - name: artis3n.tailscale
  - name: ironicbadger.docker_compose_generator

collections:
  # - name: vladgh.samba
  - name: https://github.com/vladgh/ansible-collection-vladgh-samba
    version: main
    type: git

