---
- name: Update package cache
  ansible.builtin.package:
    update_cache: true
    # cache_valid_time: 86400 # one day
  register: aptcache

- name: Upgrade packages
  ansible.builtin.package:
    upgrade: true
  tags: optional

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: false
  register: reboot_required_file

- name: Reboot if necessary
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ additional_packages }}"

- name: Install the packages I like
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ favorite_packages }}"
