---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400 # one day
  register: aptcache

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: dist
  tags: optional

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: false
  register: reboot_required_file

- name: Reboot if necessary
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ additional_packages }}"
    state: present

# - name: Install the packages I like
#   ansible.builtin.package:
#     name: "{{ favorite_packages }}"
#     state: present
#   tags: optional
