---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400 # one day

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force _apt_get: true
  when: upgrade_packages

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: false
- name: Install the packages I like
  ansible.builtin.package:
    name: "{{ favorite_packages }}"
    state: present
    