---
# defaults file for fozzie-drives
storage_opts: >
  defaults, nonempty,
  allow_other,use_ino,cache.files=off,moveonenospc=true,
  category.create=epmfs,dropcacheonclose=true,
  minfreespace=50G,fsname=mergerfs
data_opts: "subvol=@data"
content_opts: "subvol=@content"

snapraid_config_hidden_files_enabled: false
snapraid_config_hidden_files: nohidden
snapraid_config_path: /etc/snapraid.conf

## snapraid
snapraid_config_excludes:
  - "*.unrecoverable"
  - "/tmp/"
  - "/lost+found/"
  - "downloads/"
  - "appdata/"
  - "*.!sync"
  - ".AppleDouble"
  - "._AppleDouble"
  - ".DS_Store"
  - "._.DS_Store"
  - ".Thumbs.db"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - ".AppleDB"
  - ".nfo"

# snapraid drives
snapraid_parity_disks:
  - {
    path: /mnt/snapraid-parity/p1,
    src: LABEL=snapraid_p01,
    fs: ext4,
    opts: defaults,
    state: mounted,
    content: false,
  }
  - {
    path: /mnt/snapraid-parity/p2,
    src: LABEL=snapraid_p02,
    fs: ext4,
    opts: defaults,
    state: mounted,
    content: false,
  }

snapraid_data_disks:
  - {
    path: /mnt/snapraid-data/disk1,
    src: LABEL=mergerfsdisk1,
    name: mergerfsdisk1,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: []
  }
  - {
    path: /mnt/snapraid-data/disk2,
    src: LABEL=mergerfsdisk2,
    name: mergerfsdisk2,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: []
  }
  - {
    path: /mnt/snapraid-data/disk3,
    src: LABEL=mergerfsdisk3,
    name: mergerfsdisk3,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: []
  }
  - {
    path: /mnt/snapraid-data/disk4,
    src: LABEL=mergerfsdisk4,
    name: mergerfsdisk4,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: []
  }
  - {
    path: /mnt/snapraid-data/disk5,
    src: LABEL=mergerfsdisk5,
    name: mergerfsdisk5,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: [],
  }
  - {
    path: /mnt/snapraid-data/disk6,
    src: LABEL=mergerfsdisk6,
    name: mergerfsdisk6,
    fs: btrfs,
    opts: subvol=@data,
    state: mounted,
    content: false,
    vars: []
  }

snapraid_content_disks:
  - {
    path: /mnt/snapraid-content/disk1,
    src: LABEL=mergerfsdisk1,
    name: mergerfsdisk1,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }
  - {
    path: /mnt/snapraid-content/disk2,
    src: LABEL=mergerfsdisk2,
    name: mergerfsdisk2,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }
  - {
    path: /mnt/snapraid-content/disk3,
    src: LABEL=mergerfsdisk3,
    name: mergerfsdisk3,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }
  - {
    path: /mnt/snapraid-content/disk4,
    src: LABEL=mergerfsdisk4,
    name: mergerfsdisk4,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }
  - {
    path: /mnt/snapraid-content/disk5,
    src: LABEL=mergerfsdisk5,
    name: mergerfsdisk5,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }
  - {
    path: /mnt/snapraid-content/disk6,
    src: LABEL=mergerfsdisk6,
    name: mergerfsdisk6,
    fs: btrfs,
    opts: subvol=@content,
    state: mounted,
    content: true,
  }

additional_disks: []

snapraid_content_files:
  - /var/snapraid.content
  - /mnt/snapraid-content/disk1/snapraid.content
  - /mnt/snapraid-content/disk2/snapraid.content
  - /mnt/snapraid-content/disk3/snapraid.content
  - /mnt/snapraid-content/disk4/snapraid.content
  - /mnt/snapraid-content/disk5/snapraid.content
  - /mnt/snapraid-content/disk6/snapraid.content

fstab_mergerfs:
  - {
    source: "/mnt/snapraid-data/disk*",
    mountpoint: "/mnt/storage",
    fs: fuse.mergerfs,
    opts: "defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,dropcacheonclose=true,minfreespace=2G,fsname=mergerfs"
  }
