---
# - name: Copy motd file
#   ansible.builtin.template:
#     src: templates/motd.j2
#     dest: /etc/motd
#     owner: root
#     group: root
#     mode: 0444

# - name: Copy local motd file if one has been created
#   ansible.builtin.local_action: stat
#     path: "files/{{ motd_file }}"
#   register: result

- name: Copy file if it exists
  ansible.builtin.copy:
    src: "{{ motd_file }}"
    dest: "/etc/update-motd.d/01-banner"
    mode: 0755

- name: Remove 10-help-text file
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  with_items: "{{ motd_files_remove }}"
