---
- name: Copy file if it exists
  ansible.builtin.copy:
    src: "{{ motd_file }}"
    dest: "/etc/update-motd.d/01-banner"
    mode: 0755

- name: Remove 10-help-text file
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  with_items: "{{ motd_files_remove }}"
