---
- name: Ensure ZSH installed
  ansible.builtin.apt:
    name: zsh
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure zsh installed Mac
  ansible.builtin.command: brew install zsh
  args:
    creates: /usr/local/bin/zsh
  when: ansible_os_family == "Darwin"
- name: Set ZSH as the default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  when: zsh_default_shell
