---
# tasks file for bhawkins-user
- name: Ensure zsh is installed
  ansible.builtin.package:
    name: zsh
    state: present

- name: Make sure bhawkins user is created
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    groups:
      - users
      - sudo
      - adm
    createhome: true
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    state: present
  with_items: "{{ my_users }}"

# nano insists that we create this for them as their majesty won't get their
# hands dirty.
- name: Ensure that ~/.local/share dir exists
  ansible.builtin.file:
    path: "{{ item.home }}/.local/share"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0700
    state: directory
  with_items: "{{ my_users }}"

- name: Ensure dotfiles repository is cloned locally.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Debug local destination
  ansible.builtin.debug:
    msg: "{{ dotfiles_repo_local_destination }}"

- name: Try using Stow
  stow:
    state: present
    package: "{{ item }}"
    dir: "{{ dotfiles_repo_local_destination }}"
    target: "{{ dotfiles_home }}"
  with_items:
    - 'mc'
    - 'nano'
    - 'zsh'
    - 'tmux'
    - 'iterm2'
