#
# Packages
#
upgrade_packages: false
favorite_packages:
  - curl
  - git
  - htop
  - "iftop"
  - "iotop"
  # - lm-sensors #  Only for ubuntu?
  - mc
  - most
  - mutt
  - nano
  - ncdu
  - net-tools
  - open-vm-tools
  - pv
  - qemu-guest-agent
  - rsync
  - screen
  - smartmontools
  - stow
  - tmux
  - tree
  - unzip
  - util-linux
  - wget
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - cifs-utils

additional_packages: []
