---
# tasks file for fozzie-drives
- name: Ensure snapraid/mergerfs/snapper packages are installed
  ansible.builtin.package:
    name:
      - mergerfs
      - snapraid
      - snapper
    state: present

- name: Create /mnt points
  ansible.builtin.file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
    mode: 0755
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ snapraid_content_disks }}"

- name: Mount disks
  ansible.posix.mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: mounted
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ snapraid_content_disks }}"
    - "{{ additional_disks }}"
  when: item.path != '/mnt/storage'


- name: Mount mergerfs array
  ansible.posix.mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: mounted
  with_items:
    - "{{ fstab_mergerfs }}"

- name: Copy snapraid config file
  ansible.builtin.template:
    src: "snapraid.conf.j2"
    dest: "{{ snapraid_config_file }}"
    mode: 0755
    owner: root
    group: root

# - name: Configure snapper
#   ansible.builtin.include_role:
#     name: ansible-role-snapper
#   vars:
#     snapper_configs: "{{ snapraid_data_disks }}"

# Snapper configuration
- name: Include snapper setup
  ansible.builtin.include_tasks:
    file: snapper.yml
  tags: snapraid-btrfs

- name: Install/configure snapraid-btrfs
  ansible.builtin.include_tasks:
    file: snapraid-btrfs.yml
  tags: snapraid-btrfs
