---
- name: Ensure snapraid-btrfs repository is cloned locally.
  ansible.builtin.git:
    repo: "https://github.com/automorphism88/snapraid-btrfs.git"
    dest: "/opt/snapraid-btrfs"
    version: "v0.14.1"
    force: true
    # accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: true
  tags: snapraid-btrfs

- name: Copy snapraid-btrfs script to /usr/local/bin
  ansible.builtin.file:
    src: "/opt/snapraid-btrfs/snapraid-btrfs"
    dest: "{{ snapraid_btrfs_bin }}"
    mode: "0644"
    owner: "root"
    group: "root"
    state: link
  tags: snapraid-btrfs

- name: Ensure that snapraid-btrfs-runner is installed
  ansible.builtin.git:
    repo: "https://github.com/fmoledina/snapraid-btrfs-runner.git"
    dest: "/opt/snapraid-btrfs-runner"
    version: "v0.0.2"
  become: true
  tags: snapraid-btrfs

- name: Template out snapraid-btrfs-runner config file
  ansible.builtin.template:
    src: "templates/snapraid-btrfs-runner.conf.j2"
    dest: "{{ snapraid_btrfs_runner_config }}"
    mode: 0644

- name: Template out service file
# TODO: Make it a true template, with, you know, variables
  ansible.builtin.template:
    src: "templates/snapraid-btrfs-runner.service.j2"
    dest: "/etc/systemd/system/snapraid-btrfs-runner.service"
    mode: 0755
  tags: snapraid-btrfs
