---
- name: Ensure snapper is installed
  ansible.builtin.package:
    name: snapper
    state: present
  vars:
    snapper:
      timeline_create: "false"
      path: "/"

# - name: Template out the template file
#   ansible.builtin.template:
#     src: "templates/snapper-template-mergerfsdisk.j2"
#     mode: 0644

- name: Template out the config files
  ansible.builtin.template:
    src: "templates/snapper-template-mergerfsdisk.j2"
    dest: "{{ snapper_config_dir }}/{{ item.name }}"
    mode: 0644
  with_items:
    - "{{ snapraid_data_disks }}"
