---
# This file contains fixes for little Ubuntu-specific annoyances
# Like, I don't want snapd.

- name: Get rid of snapd
  ansible.builtin.package:
    name: snapd
    state: absent
    purge: true
